displayName: theme.park

summary: Apply themes from [theme.park](theme-park.dev) to supported applications.

type: middleware

import: github.com/packruler/traefik-themepark

testData:
  app: sonarr
  theme: dark

iconPath: https://docs.theme-park.dev/site_assets/logo.png
bannerPath: https://github.com/GilbN/theme.park/blob/master/banners/tp_banner.png
