displayName: theme.park Plugin

summary: Apply themes from [theme.park](theme-park.dev) to supported applications.

type: middleware

import: github.com/packruler/plugin-themepark

testData:
  lastModified: true
  rewrites:
    - regex: "bar"
      replacement: "foo"
